#include <adiak.hpp>
#include <caliper/cali.h>

#include "lulesh.h"

void TimestampSync()
{
    static int count = 0;

    cali_id_t attr =
        cali_create_attribute("ts.sync", CALI_TYPE_INT, CALI_ATTR_DEFAULT);
    cali_variant_t val =
        cali_make_variant_from_int(count++);

#if USE_MPI
    MPI_Barrier(MPI_COMM_WORLD);
#endif
    cali_push_snapshot(CALI_SCOPE_PROCESS | CALI_SCOPE_THREAD, 1, &attr, &val);
}

// defined in lulesh-build-metadata.cc, which is generated by cmake
extern const char* buildMetadata[][2];

void RecordGlobals(const cmdLineOpts& opts, int num_threads)
{
    adiak::user();
    adiak::launchdate();
    adiak::executablepath();
    adiak::cmdline();
    adiak::clustername();
    adiak::jobsize();
    adiak::numhosts();
    adiak::hostlist();

    adiak::value("threads", num_threads);

    adiak::value("iterations", opts.its);
    adiak::value("problem_size", opts.nx);
    adiak::value("num_regions", opts.numReg);
    adiak::value("region_cost", opts.cost);
    adiak::value("region_balance", opts.balance);

    // add build metadata
    for (size_t i = 0; buildMetadata[i][0]; ++i)
       adiak::value(buildMetadata[i][0], buildMetadata[i][1]);
}
